server:
  port: 9001

spring:
  application:
    name: user-service

  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: 121.36.81.39:8848
        password: 992184xiang.
        username: nacos

  redis:
    host: 121.36.81.39
    password: 123456
    port: 6379

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.81.39:3306/cilicili?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 992184xiang.



aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tL14tpRQPtJ9iJigNVg
    access-key-secret: Q8QqRLun9JmcyFhlESU2WUakMgoN8J
    bucket-name: cilicili-useravatar
  message:
    endpoint: dysmsapi.aliyuncs.com
    access-key-id: LTAI5tEG5i9j4FwD8r8VwFhK
    access-key-secret: 2oqe7qsP7dqNyZAUnkEHbBWXAV4u5q

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

#配置feign
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000